# Generated by Django 3.2.3 on 2021-05-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Select language book is written in', to='catalog.Language'),
        ),
    ]
