# Generated by Django 3.2.3 on 2021-05-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210530_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_Img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
